### ISSUE TITLE
printf warning when using -debug

### ISSUE THREAD

**Issue by jvanderzande** [peterhaijen/vimexx-dns#1]
Hi Peter,
Thanks for this nice perl script. 
Just for your info: I found a minor issue on line 324 when using -debug:

`printf("Succesfully updated DNS records.\n", scalar @{$data{'body'}{'dns_records'}}) if $config->verbose;`

should be:

`printf("Succesfully updated %d DNS records.\n", scalar @{$data{'body'}{'dns_records'}}) if $config->verbose;`

... to avoid a warning in the output. (too minor for creating a fork and a PR ;) )
Thanks again,
Jos

**Comment by peterhaijen** [comment]
Hi Jos

Thanks for letting me know! I've committed your fix.

Peter
